[features]
seeds = false
[programs.localnet]
cgc_token_swap = "7xMKTCKBjfhaNveXaLnZk6qaP1XdbTM7UBptNxcwGcwD"

[programs.devnet]
nft_marketplace = "7xMKTCKBjfhaNveXaLnZk6qaP1XdbTM7UBptNxcwGcwD"

[programs.mainnet]
nft_marketplace = "7xMKTCKBjfhaNveXaLnZk6qaP1XdbTM7UBptNxcwGcwD"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/home/alex/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/home/alex/blockchain/Keys/alex.json"

#[provider]
#cluster = "mainnet"
#wallet = "/home/alex/blockchain/Keys/alex.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
